name: 🐞 Сообщить о проблеме
description: Сообщите о проблеме, чтобы помочь улучшить проект.
labels: ["bug"]
assignees:
  - rx1310
body:
  - type: markdown
    attributes:
      value: Спасибо за то, что помогаете проекту стать лучше! Пожалуйста, заполните все формы максимально подробно, чтобы у разработчиков не осталось вопросов (или осталось, но намного меньше).
  - type: textarea
    id: what-happened
    attributes:
      label: Что случилось?
      description: Расскажите нам о проблеме максимально подробно. Блоки кода, логи и скриншоты также приветствуются.
      placeholder: Расскажите нам всё!
      value: "При использовании миксина `prefixer` не удает..."
    validations:
      required: true
  - type: dropdown
    id: versionKalium19
    attributes:
      label: Версия Kalium19
      description: |
        Какую версию Kalium19 вы использовали в своем проекте?

        **Подсказка**: версию можно узнать в файле *package.json* вашего проекта
      options:
        - 4.x (alpha)
        - 3.x
        - 2.x (deprecated)
        - 1.x (deprecated)
        - 0.x (deprecated)
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Лог консоли
      description: Пожалуйста, скопируйте лог (вывод) консоли при сборке и вставьте сюда (если он есть).
      render: shell
  - type: markdown
    attributes:
      value: "## Рабочее окружение"
  - type: dropdown
    id: envOS
    attributes:
      label: Операционная система
      description: Выберите семейство вашей операционной системы, на которой наблюдается эта проблема
      multiple: true
      options:
        - Microsoft Windows
        - Linux-based
        - macOS
        - Android (Termux)
        - BSD?
    validations:
      required: true